import localFont from "next/font/local";
import { Outfit} from 'next/font/google';
import './globals.css'

  const bricolage = localFont({
    src: "../../public/fonts/BricolageGrotesque_72pt-Medium.ttf",
    fallback: ['ui-sans-serif', 'system-ui', 'sans-serif'],                                                                                                                                                                                                                       
  });
  const Outfitfont = Outfit(
    {
      subsets: ['latin'],
      weight: ['300', '400', '700',  '900'],
      fallback: ['Placeholder' ,'sans-serif']

    }
  )
  export const metadata = {
    title: "Tweatflash | Join the revolution where your 'Thoughts' earn rewards",
    description: "Generated by create next app",
  };
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {

  return (
    <html lang="en" className='dark' data-theme=''>
        <link href="https://fonts.googleapis.com/css2?family=Outfit&display=swap" rel="stylesheet"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"></meta>
        <body className={`${Outfitfont.className} flex justify-center bg-[hsl(var(--background))]`}>
            {children}
        </body>
    </html>
  )
   
}
