import localFont from "next/font/local";
import { Montserrat} from 'next/font/google';
import './globals.css'
import { GoogleOAuthProvider } from '@react-oauth/google';
  const bricolage = localFont({
    src: "../../public/fonts/Matter-Regular.ttf",                                                                                                                                                                                                                    
  });
  const Outfitfont = Montserrat(
    {
      subsets: ['latin'],
      weight: ['300', '400', '700', ],
      fallback: ["Inter","Inter Placeholder","sans-serif"]
      

    }
  )

  export const metadata = {
    title: "Tweatflash | Join the revolution where your 'Thoughts' earn rewards",
    description: "Generated by create next app",
  };
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {

  return (
    <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}>
      <html lang="en" className='dark' data-theme=''>
          {/* <link href="https://fonts.googleapis.com/css2?family=Outfit&display=swap" rel="stylesheet"/> */}
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"></meta>
          <body className={`${bricolage.className} w-full `}>
              
                {children}
              
          </body>
      </html>
    </GoogleOAuthProvider>
  )
   
}
